Repository googleapis/nodejs-channel, pull requests merged in 2021-03, with the labels that each got.

#17 feat: addition of billing_account field on Plan. docs: clarification that valid address lines are required for all customers.
  protos/google/cloud/channel/v1/customers.proto
  protos/google/cloud/channel/v1/offers.proto
  protos/google/cloud/channel/v1/service.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/cloud_channel_service_client.ts
  synth.metadata
Labels: api: cloudchannel, cla: yes, context: full

#19 build: update gapic-generator-typescript to v1.2.10.
  synth.metadata
  webpack.config.js
Labels: api: cloudchannel, automerge, cla: yes, context: full

#20 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  synth.metadata
  synth.py
Labels: api: cloudchannel, cla: yes
