Repository googleapis/nodejs-channel, pull requests merged in 2021-02, with the labels that each got.

#10 chore: update CODEOWNERS config
  .github/CODEOWNERS
Labels: automerge, cla: yes

#9 build: migrate to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
Labels: automerge, cla: yes

#11 feat: add Pub/Sub endpoints for Cloud Channel API
  .jsdoc.js
  CONTRIBUTING.md
  README.md
  linkinator.config.json
  protos/google/cloud/channel/v1/service.proto
  protos/google/cloud/channel/v1/subscriber_event.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  samples/README.md
  src/v1/cloud_channel_service_client.ts
  src/v1/cloud_channel_service_client_config.json
  src/v1/cloud_channel_service_proto_list.json
  src/v1/gapic_metadata.json
  synth.metadata
  test/gapic_cloud_channel_service_v1.ts
Labels: cla: yes, context: partial

#14 chore: update flakybot config
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: cla: yes, context: partial

#16 docs: Documentation update BREAKING CHANGE: TransferableSkus field deprecation. Okay to make this change since no clients are using the libraries that were released just last week. The fields were supposed to be deprecated but missed. We have communi
  protos/google/cloud/channel/v1/channel_partner_links.proto
  protos/google/cloud/channel/v1/common.proto
  protos/google/cloud/channel/v1/customers.proto
  protos/google/cloud/channel/v1/entitlements.proto
  protos/google/cloud/channel/v1/offers.proto
  protos/google/cloud/channel/v1/operations.proto
  protos/google/cloud/channel/v1/products.proto
  protos/google/cloud/channel/v1/service.proto
  protos/google/cloud/channel/v1/subscriber_event.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/cloud_channel_service_client.ts
  synth.metadata
Labels: api: cloudchannel, cla: yes, context: full
